# netlify toml configuration
[build]
base = "./"
publish = "./dist/angular-clean-architecture-serverless/"
command = "ng build"

[functions]
directory = "/netlify/functions/"
external_node_modules = ["mongodb", "netlify"]
