# netlify toml configuration
[build]
base = "./"
publish = "./dist/angular-clean-architecture-serverless/"
command = "ng build"
edge_functions = "/netlify/functions/"

# [[redirects]]
# from = "/*"
# to = "/index.html"
# status = 200

[functions]
directory = "./netlify/functions"
external_node_modules = ["mongodb", "netlify"]
